[package]
name = "ntnu-thesis"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["Theodor Johansson", "Rafael Oliveira <@RafDevX>"]
license = "MIT AND MIT-0"
description = "Unofficial thesis template for NTNU (Forked from RafDevX)"
repository = "https://github.com/Th3o4oR/ntnu-thesis"
categories = ["thesis", "layout"]
keywords = [
    "NTNU",
    "Norwegian University of Science and Technology",
    "master",
    "thesis",
]
compiler = "0.15.0"
exclude = [".gitignore", "*.sh"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
